// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOJU8NUJTmuXr42orFCoPx407jO_FWHo',
    appId: '1:517436413804:web:049a7275c9da18adcc4549',
    messagingSenderId: '517436413804',
    projectId: 'pizza-369',
    authDomain: 'pizza-369.firebaseapp.com',
    storageBucket: 'pizza-369.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ-4X370T-nNuOFw-DvdtjAFwYPueEQa0',
    appId: '1:517436413804:android:e915f484544dc1cacc4549',
    messagingSenderId: '517436413804',
    projectId: 'pizza-369',
    storageBucket: 'pizza-369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdv3c_jSB889C3Dus2oiW3NBOomCCmWhQ',
    appId: '1:517436413804:ios:da32112039e5a3e6cc4549',
    messagingSenderId: '517436413804',
    projectId: 'pizza-369',
    storageBucket: 'pizza-369.appspot.com',
    iosClientId: '517436413804-cr93obccb1hsn4ng1t8hr3jrio3dj7jn.apps.googleusercontent.com',
    iosBundleId: 'com.patrickkoszewski.pizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdv3c_jSB889C3Dus2oiW3NBOomCCmWhQ',
    appId: '1:517436413804:ios:da32112039e5a3e6cc4549',
    messagingSenderId: '517436413804',
    projectId: 'pizza-369',
    storageBucket: 'pizza-369.appspot.com',
    iosClientId: '517436413804-cr93obccb1hsn4ng1t8hr3jrio3dj7jn.apps.googleusercontent.com',
    iosBundleId: 'com.patrickkoszewski.pizza',
  );
}
